seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: /home/tungnd/atmos-arena/experiments/fingerprint

  precision: 16

  devices: null
  num_nodes: 1
  accelerator: gpu
  strategy: ddp

  min_epochs: 1
  max_epochs: 50
  enable_progress_bar: true

  sync_batchnorm: True
  enable_checkpointing: True
  num_sanity_val_steps: 1

  # debugging
  fast_dev_run: false

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      entity: 'tungnd'
      project: 'atmos-arena'
      save_dir: ${trainer.default_root_dir}/fingerprint_climax_5.625_finetune_backbone_128bs_5e-4_lr
      name: fingerprint_climax_5.625_finetune_backbone_128bs_5e-4_lr

  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/fingerprint_climax_5.625_finetune_backbone_128bs_5e-4_lr/checkpoints"
        monitor: "val/w_mse" # name of the logged metric which determines when model is improving
        mode: "min" # "max" means higher metric value is better, can be also "min"
        save_top_k: 1 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: False
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False

    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val/w_mse" # name of the logged metric which determines when model is improving
        mode: "min" # "max" means higher metric value is better, can be also "min"
        patience: 10 # how many validation epochs of not improving until training stops
        min_delta: 0. # minimum change in the monitored metric needed to qualify as an improvement

    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: lightning.pytorch.callbacks.TQDMProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 5e-4
  beta_1: 0.9
  beta_2: 0.999
  weight_decay: 1e-5
  warmup_epochs: 5
  max_epochs: 50
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  pretrained_path: https://huggingface.co/tungnd/climax/resolve/main/5.625deg.ckpt
  # pretrained_path: https://huggingface.co/tungnd/climax/resolve/main/1.40625deg.ckpt

  net:
    class_path: fingerprint.climax_fingerprint_arch.ClimaXFingerprint
    init_args:
      img_size: [64, 128]
      default_vars: ['surface_air_temperature', 'surface_specific_humidity', 'precipitation']
      patch_size: 2
      embed_dim: 1024
      depth: 8
      decoder_depth: 2
      num_heads: 16
      mlp_ratio: 4
      drop_path: 0.1
      drop_rate: 0.1
      freeze_encoder: False

# ---------------------------- DATA -------------------------------------------
data:
  hf_path: sungduk/wip_cmip6_v2.2
  in_variables: ['surface_air_temperature', 'surface_specific_humidity', 'precipitation']
  batch_size: 16
  num_workers: 4
  pin_memory: False